<a href="https://colab.research.google.com/github/Abhi23run/Data-Science-/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def sum(x,y):
    """
    This function ret Azurns the sum of 2 numbers 
    """
    print(f"sum of the 2 numbers is {x+y:.2f}")

In [ ]:
k=sum(2.459,3.2) '

sum of the 2 numbers is 5.66


In [ ]:
print(k)

None


In [ ]:
s="abhinav"

In [ ]:
a,b,*_=s

In [ ]:
':'.join(_)

'h:i:n:a:v'

In [ ]:
players=[["rohit","virat","shikhar"],["warner","aaron","maxwell"]]

In [ ]:
[k for i in players for k in i if k.count("a")>1]

['aaron']

In [ ]:
a=2
def transf():
    #global a
    a=3

In [ ]:
transf()

In [ ]:
a

2

In [ ]:
states = ["   Alabama ", "Georgia!", "Georgia", "georgia", "FlOrIda",  "south   carolina##", "West virginia?"]

In [ ]:
states

In [ ]:
def squares(n=10):
    for i in range(n+1):
        yield i**2

In [ ]:
gen=squares()

In [ ]:
gen

<generator object squares at 0x124eabdd0>

In [ ]:
next(gen)

4

In [ ]:
gen_1=((i,i**2) for i in range(5))

In [ ]:
dict([(1,1),(2,2)])

{1: 1, 2: 2}

# Itertools module for generators 

In [ ]:
import itertools

In [ ]:
k=itertools.groupby(["Rohit","Rahul","Pant","Dhoni"],key=lambda x:x.count("h"))

In [ ]:
for i,j in k:
    print(i,list(j))

1 ['Rohit', 'Rahul']
0 ['Pant']
1 ['Dhoni']


In [ ]:
list(itertools.combinations([1,2,3],2))

[(1, 2), (1, 3), (2, 3)]

In [ ]:
list(itertools.permutations([1,2,3],2))

# Intro to Numpy

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])
a=a.astype(np.float64)

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a

array([1., 2., 3.])

In [ ]:
%timeit a*a

275 ns ± 0.896 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
a*a

array([1., 4., 9.])

In [ ]:
np.eye(2).shape

(2, 2)

In [ ]:
a=np.arange(3)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b=np.array([1,2,3],dtype='float32')

In [ ]:
a.astype(b.dtype)

In [ ]:
names=np.array(["Bob","Ann","Bob","Alex","Ann","Bob"])

In [ ]:
scores=np.ones((6,2))

In [ ]:
scores[3]=7

In [ ]:
scores[:,1:]=2

In [ ]:
scores[names=='Ann']

array([[1., 2.],
       [1., 2.]])

In [ ]:
scores

array([[1., 2.],
       [1., 2.],
       [1., 2.],
       [7., 2.],
       [1., 2.],
       [1., 2.]])

In [ ]:
# fancy indexing 
scores[[2,3,5]][:,[1]]

## numpy random number generator

In [ ]:
import numpy as np

In [ ]:
print(dir(np.random))

['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'PCG64DXSM', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bounded_integers', '_common', '_generator', '_mt19937', '_pcg64', '_philox', '_pickle', '_sfc64', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'tria

In [ ]:
rng=np.random.default_rng(1234)

In [ ]:
print(dir(rng))

['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '_bit_generator', '_poisson_lam_max', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'gumbel', 'hypergeometric', 'integers', 'laplace', 'logistic', 'lognormal', 'logseries', 'multinomial', 'multivariate_hypergeometric', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'permuted', 'poisson', 'power', 'random', 'rayleigh', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


In [ ]:
rng.uniform(0,1,(2,2))

array([[0.11809123, 0.24176629],
       [0.31853393, 0.96407925]])

In [ ]:
a=np.array([1,2,3])
b=np.array([2,2,4])

In [ ]:
np.power(a,b)

array([ 1,  8, 81])

In [ ]:
a={1,2,3}
b={2,3,4}

In [ ]:
np.logical_xor(a,b)

array([False, False, False])

In [ ]:
a=[1,1,0]
b=[1,1,1]
np.logical_xor(a,b)

array([False, False,  True])

In [ ]:
3==4

False

In [ ]:
np.arange(-5,5,0.01)

(1000,)

In [ ]:
import numpy as np

In [ ]:
a=np.array([[1,2,3],[4,5,6]])

In [ ]:
i,j=a.shape
n_elements=i*j

In [ ]:
n_elements

6

In [ ]:
average_mat=a.sum()/n_elements

In [ ]:
np.where(a>average_mat,1,-1).cumsum(axis=0)

array([[-1, -1, -1],
       [ 0,  0,  0]])

In [ ]:
np.in1d(a[a>average_mat],[5])

array([False,  True, False])

In [ ]:
ind=['rohit','virat','pant']
eng=['root','sam','jos']
flag=[1,0,1]
np.where(flag,ind,eng)